#!/bin/bash

echo "🚀 PadelCast Cloud Deployment to Render"
echo "========================================"
echo ""
echo "📋 Prerequisites:"
echo "1. Create a GitHub repository with your code"
echo "2. Sign up at https://render.com"
echo "3. Have a credit card ready (for verification only)"
echo ""
echo "🔗 Steps to deploy:"
echo ""
echo "1. Push your code to GitHub:"
echo "   git init"
echo "   git add ."
echo "   git commit -m 'Initial commit'"
echo "   git remote add origin YOUR_GITHUB_REPO_URL"
echo "   git push -u origin main"
echo ""
echo "2. Go to https://render.com and:"
echo "   - Click 'New +' → 'Web Service'"
echo "   - Connect your GitHub repository"
echo "   - Set Build Command: pip install -r requirements.txt"
echo "   - Set Start Command: gunicorn --worker-class eventlet -w 1 app:app --bind 0.0.0.0:$PORT"
echo "   - Choose 'Free' plan"
echo ""
echo "3. Your app will be deployed at:"
echo "   https://your-app-name.onrender.com"
echo ""
echo "4. Update your iPhone app with the new URL!"
echo ""
echo "✅ That's it! Your PadelCast will be running in the cloud!"
